import { test, expect } from '@playwright/test'

test('nested helpers reset leaves, keep siblings, update defaults and remember drafts', async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.goto('/forms')
  const name = page.getByRole('textbox', {name: 'Student name', exact: true})
  const email = page.getByRole('textbox', {name: 'Student email', exact: true})
  await name.fill('Grace')
  await email.fill('keep@example.test')
  await page.getByRole('textbox', {name: 'First lesson', exact: true}).fill('Code')
  await page.getByRole('textbox', {name: 'Second lesson', exact: true}).fill('Music')
  await page.getByRole('button', {name: 'Add example errors'}).click()
  await page.getByRole('button', {name: 'Reset name + error'}).click()
  await expect(name).toHaveValue('Ada')
  await expect(email).toHaveValue('keep@example.test')
  await expect(page.getByRole('alert')).toHaveText('Example email error')
  await page.getByRole('button', {name: 'Reset first lesson'}).click()
  await expect(page.getByRole('textbox', {name: 'First lesson', exact: true})).toHaveValue('Math')
  await expect(page.getByRole('textbox', {name: 'Second lesson', exact: true})).toHaveValue('Music')
  await name.fill('New default')
  await page.getByRole('button', {name: 'Make name the default'}).click()
  await name.fill('Temporary')
  await page.getByRole('button', {name: 'Reset name + error'}).click()
  await expect(name).toHaveValue('New default')
  await page.getByRole('link', {name: 'Back to About'}).click()
  await page.goBack()
  await expect(name).toHaveValue('New default')
  await expect(email).toHaveValue('keep@example.test')
  await expect(page.getByRole('alert')).toHaveText('Example email error')
  await page.getByRole('button', {name: 'Reset everything'}).click()
  await expect(page.getByText('Form dirty: false', {exact: true})).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
})
